trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# 1️⃣ Install .NET SDK
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'

# 2️⃣ Restore dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 3️⃣ Build the project
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 4️⃣ Run tests with code coverage
- task: DotNetCoreCLI@2
  displayName: 'Run tests with code coverage'
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
    publishTestResults: true

# 5️⃣ Generate Cobertura code coverage report using ReportGenerator task
- task: ReportGenerator@5
  displayName: 'Generate Cobertura code coverage report'
  inputs:
    reports: '**/TestResults/*/coverage.cobertura.xml'   # Path to coverage files
    targetdir: '$(Build.ArtifactStagingDirectory)/CoverageReport' # Output folder
    reporttypes: 'Cobertura;HtmlInline_AzurePipelines'   # Generate Cobertura XML + HTML report
    failTaskOnEmptyReports: true

# 6️⃣ Publish code coverage results to Azure DevOps
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.ArtifactStagingDirectory)/CoverageReport/Cobertura.xml'
    reportDirectory: '$(Build.ArtifactStagingDirectory)/CoverageReport'
    failIfCoverageEmpty: true

# 7️⃣ Publish the project artifacts
- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# 8️⃣ Publish build artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'