trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# 1️⃣ Install .NET SDK 6
- task: UseDotNet@2
  displayName: 'Install .NET SDK 6'
  inputs:
    packageType: 'sdk'
    version: '8.x'

# 2️⃣ Restore dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 3️⃣ Build the project
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 4️⃣ Run tests with code coverage
- task: DotNetCoreCLI@2
  displayName: 'Run tests with code coverage'
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
    publishTestResults: true
# 7️⃣ Publish code coverage results using v2 (recommended)
- task: PublishCodeCoverageResults@2
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
    reportDirectory: '$(Build.ArtifactStagingDirectory)/CoverageReport'
    failIfCoverageEmpty: true

# 8️⃣ Publish the project artifacts
- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# 9️⃣ Publish build artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'