trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# 1️⃣ Install .NET SDK
- task: UseDotNet@2
  displayName: 'Install .NET SDK 6'
  inputs:
    packageType: 'sdk'
    version: '6.x'

# 2️⃣ Restore dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 3️⃣ Build the project
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 4️⃣ Run tests with code coverage
- task: DotNetCoreCLI@2
  displayName: 'Run tests with code coverage'
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
    publishTestResults: true

# 5️⃣ List coverage files (optional debug step)
- powershell: |
    Write-Host "Searching for coverage files..."
    Get-ChildItem -Path "$(System.DefaultWorkingDirectory)" -Recurse -Filter "coverage.cobertura.xml" | ForEach-Object { Write-Host $_.FullName }
  displayName: 'List coverage files'

# 6️⃣ Generate Cobertura code coverage report
- task: ReportGenerator@5
  displayName: 'Generate Cobertura code coverage report'
  inputs:
    reports: '**/TestResults/*/coverage.cobertura.xml'
    targetdir: '$(Build.ArtifactStagingDirectory)/CoverageReport'
    reporttypes: 'Cobertura;HtmlInline_AzurePipelines'
    failTaskOnEmptyReports: true

# 7️⃣ Publish code coverage results to Azure DevOps
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.ArtifactStagingDirectory)/CoverageReport/Cobertura.xml'
    reportDirectory: '$(Build.ArtifactStagingDirectory)/CoverageReport'
    failIfCoverageEmpty: true

# 8️⃣ Publish the project artifacts
- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# 9️⃣ Publish build artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'